//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoEstadoBodega.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibroDiario
    {
        public int ID { get; set; }
        public int id_TipoEmpaque { get; set; }
        public int id_Empresa { get; set; }
        public int id_Trasladodespacho { get; set; }
        public int id_Valija { get; set; }
        public string Destino { get; set; }
        public string Comuna { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public string CodigoSeguimiento { get; set; }
        public int id_TipoCampaña { get; set; }
        public string CampañaObs { get; set; }
        public int id_Area { get; set; }
        public string Mandante { get; set; }
        public string Receptor { get; set; }
        public int Bultos { get; set; }
        public string Obs { get; set; }
        public int id_Meca { get; set; }
        public int id_TipoDespacho { get; set; }
        public int id_TipoEncomienda { get; set; }
        public Nullable<int> costedespacho { get; set; }
        public Nullable<int> costeMeca { get; set; }
        public Nullable<int> TotalMeca { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual TipoEmpaque TipoEmpaque { get; set; }
        public virtual Mecanizado Mecanizado { get; set; }
        public virtual TipoCampaña TipoCampaña { get; set; }
        public virtual TrasladoDespacho TrasladoDespacho { get; set; }
        public virtual ValijaInterna ValijaInterna { get; set; }
        public virtual TipoDespacho TipoDespacho { get; set; }
        public virtual TipoEncomienda TipoEncomienda { get; set; }
    }
}
