//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoEstadoBodega.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicioMoto
    {
        public int MotoID { get; set; }
        public string DireccionRetiro { get; set; }
        public string DireccionEntrega { get; set; }
        public string PersonaRecibe { get; set; }
        public string Descripcion { get; set; }
    }
}
