//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoEstadoBodega.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int idStock { get; set; }
        public Nullable<int> idProducto { get; set; }
        public string ubicacion { get; set; }
        public Nullable<long> cantidadTotal { get; set; }
        public Nullable<int> cantidadPorCaja { get; set; }
        public Nullable<int> cantidadQuilicura { get; set; }
        public Nullable<int> cantidadDardignac { get; set; }
        public Nullable<System.DateTime> fechaVencimiento { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
